### ISSUE TITLE
[BUG] Gamestate player object in handelFarsightData not being filled

### ISSUE THREAD

**Issue by Weltregierung** [rcv-prod-toolkit/module-league-in-game#23]
Hello, i found a bug in the software. I wanted to create a pull request but im missing the rights to do so.

File: InGameState.ts
Line: 250
```
if (this.gameState.player[player].summonerName !== champion.displayName && this.gameState.player[player].championName !== champion.name) continue
```
The two datasets a using different naming conventions.

![grafik](https://github.com/rcv-prod-toolkit/module-league-in-game/assets/61458387/0d25ff67-623c-4599-a059-940d42399e22)

champion.name does not use ' 
This leads to the if clause being true in some cases where a champion has an ' in the name.

Possible solution:
Replace the ' in the if clause
```
if (this.gameState.player[player].summonerName !== champion.displayName && this.gameState.player[player].championName.replace("'","") !== champion.name) continue
```

**Comment by Himyu** [comment]
This issue was fixed with the newest addition to this module
